young-02/BeMyDesk

components/mypage/contents/MyFollow.tsx, components/mypage/contents/MyPost.tsx, components/mypage/contents/MyScrap.tsx, components/mypage/editProfile/ChangePassword.tsx, components/mypage/editProfile/ChangeProfile.tsx, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/mypage/index.tsx
components/mypage/contents/MyFollow.tsx
팔로우 보기 기본양식 추가
components/mypage/contents/MyPost.tsx
마이포스트 보기 기본 기능 구현
components/mypage/contents/MyScrap.tsx
마이스크랩 기본 기능 구현
components/mypage/editProfile/ChangePassword.tsx
내정보수정 - 비밀번호 변경 유효성 버그 수정
내정보수정 - 닉네임, 자기소개 변경 유효성 버그 수정, 닉네임 인풋 활성화시 focus 이동기능 구현
정보 불러오기 기본 기능 구현
=> mypage 게시물 보여주기, 닉네임수정 클릭시 focus 설정

components/post-list/Comment/CommentList.tsx, components/post-list/Comment/CommentWrite.tsx, components/ui/CustomButton.tsx, components/ui/CustomModal.tsx, pages/auth/sign-up/index.tsx, styles/globals.css
page > sign-up > index.tsx
-회원가입 기능 및 UI 추가
=> 회원가입 기능 및 UI 추가

components/Hooks/useGetReaction.tsx, components/detail/DetailView.tsx, components/detail/DetailViewProducts.tsx, components/detail/DetailViewText.tsx, components/detail/DetailViewUserInfor.tsx, components/ui/CustomModal.tsx, shared/type.d.ts
DetailViewUserInfor
- 로그아웃시 팔로우, 스크랩 버그수정
=> 로그아웃시 팔로우, 스크랩 버그수정 

components/mypage/contents/MyFollow.tsx, components/mypage/contents/MyPost.tsx, components/mypage/contents/MyScrap.tsx
components/mypage/contents/MyFollow.tsx
components/mypage/contents/MyPost.tsx
components/mypage/contents/MyScrap.tsx
마이페이지 CSS 작업
=> 💄: mypage CSS 작업

components/detail-write/DetailWriteForm.tsx
- 모달창 안의 input을 누르면 새로고침되는 문제 때문에 다시 원래 코드로 변경합니다
=> 다시 원래 코드로 변경

components/detail-write/DetailWriteForm.tsx
=> 잡카테고리 중 기획자를 게이머로 변경합니다 

components/mypage/ProfileEditModal.tsx, components/mypage/editProfile/ChangePassword.tsx, components/ui/CustomButton.tsx, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx, pages/mypage/index.tsx
프로필수정 버그수정
components/mypage/editProfile/ChangePassword.tsx
프로필수정 비밀번호변경 오류수정
components/ui/CustomButton.tsx
커스텀버튼 어트리뷰트 추가
pages/auth/sign-in/index.tsx
로그인 유효성 수정
회원가입 유효성 수정
마이페이지 CSS 수정
=> ✨: 로그인, 회원가입 유효성 버그 수정, 회원가이 이메일 직접입력 삭제(임시) #33

components/GlobalNavigationBar.tsx, components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteProductCard.tsx, components/detail-write/DetailWriteSearch.tsx, components/detail/DetailViewProducts.tsx, components/detail/DetailViewSlide.tsx, components/detail/DetailViewUserInfor.tsx, components/mypage/ProfileEditModal.tsx, components/mypage/contents/MyFollow.tsx, components/mypage/contents/MyPost.tsx, components/mypage/contents/MyScrap.tsx, components/post-list/PostListItem.tsx, next.config.js, pages/auth/sign-in/index.tsx, pages/mypage/index.tsx
components/GlobalNavigationBar.tsx
components/detail/DetailViewSlide.tsx
components/detail/DetailViewUserInfor.tsx
components/mypage/contents/MyFollow.tsx
components/mypage/contents/MyPost.tsx
components/mypage/contents/MyScrap.tsx
components/post-list/PostListItem.tsx
- img 태그 => Image 태그 변환
=> img 태그 -> Image 태그 수정

components/GlobalNavigationBar.tsx, components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteFormEditor.tsx, components/detail-write/DetailWriteProductCard.tsx, components/detail-write/DetailWriteSearch.tsx, components/detail/DetailView.tsx, components/post-list/Comment/CommentWrite.tsx, components/ui/CustomButton.tsx, pages/detail/write/[id]/edit.tsx, pages/detail/write/index.tsx, shared/type.d.ts
components/GlobalNavigationBar.tsx
- GNB 글쓰기란에 Link를 추가했습니다
- updateDoc을 추가하고 커스텀 버튼을 적용했습니다
- swiper를 적용하여 선택한 제품이 가로 슬라이드로 나오게 합니다
components/detail-write/DetailWriteFormEditor.tsx
- 에디터에 안 쓰는 props를 삭제했습니다 
shared/type.d.ts
- 오타 수정
pages/detail/write/index.tsx
- create 상태일 때 initialValue를 빈 값으로 추가합니다 
pages/detail/write/[id]/edit.tsx
- edit 페이지를 만들어서 추가합니다 
components/ui/CustomButton.tsx
- 커스텀 버튼에 속성을 추가합니다
components/post-list/Comment/CommentWrite.tsx
- 코멘트 댓글쓰기 버튼 폰트 사이즈를 수정합니다
- 수정하기 버튼을 만들어 수정을 누르면 수정페이지로 이동합니다
components/detail-write/DetailWriteSearch.tsx
- 커스텀 버튼을 적용하고 태그명을 정리 및 수정했습니다
=> update 추가, 커스텀 버튼 적용(WIP)

components/Hooks/useGetReaction.tsx, components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteProductCard.tsx, pages/auth/sign-in/index.tsx, pages/detail/write/[id]/edit.tsx, pages/mypage/index.tsx
components/Hooks/useGetReaction.tsx
- useEffect 수정
- useCallback 수정
- map key 수정
pages/detail/write/[id]/edit.tsx
- 컴포넌트 소문자 -> 대문자 수정
=> 배포 테스트 에러 수정

pages/detail/write/[id]/edit.tsx
pages/detail/write/[id]/edit.tsx
- useEffect 배포에러 수정
=> 🔨 Fix: useEffect 배포에러 수정

components/Hooks/useFilter.tsx, pages/detail/write/[id]/edit.tsx, shared/type.d.ts
components/Hooks/useFilter.tsx
shared/type.d.ts
- useFillter 타입 에러 임시 수정
=> useFillter 타입 에러 임시 수정

pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx
pages/auth/sign-in/index.tsx
regex 오류 수정
SNS 추가정보입력 CSS 작업
=> 💄: 닉네임 중복검사 CSS 작업

components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteProductCard.tsx, components/detail/DetailViewProducts.tsx
- https://be-my-desk-git-dev-young-02.vercel.app로 get 요청 url 변경
- data 이름을 images -> image, url -> link, hashTag->category2로 변경
- data 이름을 images -> image, url -> link, hashTag->category2로 변경
components/detail/DetailViewProducts.tsx
- data 이름을 images -> image, url -> link, hashTag->category2로 변경
=> naverData get 요청 url 수정, data 이름 변경

components/mypage/editProfile/ChangeProfile.tsx, next.config.js, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx
프로필수정 닉네임 중복검사 추가
next.config.js
URL 추가
pages/auth/sign-in/index.tsx
SNS 회원 첫 가입시 추가정보 입력으로 이동
회원가입시 닉네임 중복검사 추가
SNS 회원 첫가입시 추가정보 입력
=> ✨: 회원가입, SNS회원가입, 프로필 수정 닉네임 중복검사 구현 #31 #35

components/mypage/ProfileEditModal.tsx, components/mypage/editProfile/ChangeProfile.tsx, components/mypage/editProfile/DeleteAccount.tsx, pages/auth/sign-in/index.tsx
모달 회원탈퇴 추가
components/mypage/editProfile/DeleteAccount.tsx
회원탈퇴 추가
=> Feat/mypage 회원탈퇴 추가

components/mypage/CategoryButton.tsx, components/mypage/ProfileEditModal.tsx, components/mypage/editProfile/ChangePassword.tsx, components/mypage/editProfile/ChangeProfile.tsx, components/mypage/editProfile/DeleteAccount.tsx, pages/auth/find-password/index.tsx, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx, pages/mypage/index.tsx
pages/auth/find-password/index.tsx
비밀번호 찾기페이지 CSS작업
components/mypage/CategoryButton.tsx
components/mypage/editProfile/ChangePassword.tsx
components/mypage/editProfile/DeleteAccount.tsx
pages/auth/sign-in/index.tsx
버튼 호버 작업
전반적인 레이아웃 수정
=> 비밀번호 찾기페이지 CSS작업, 전체페이지 버튼 호버넣기

Hooks/useCheckUser.tsx, Hooks/useUserReauthentification.tsx, components/mypage/CategoryButton.tsx, components/mypage/ProfileEditModal.tsx, components/mypage/editProfile/ChangePassword.tsx, components/mypage/editProfile/ChangeProfile.tsx, components/mypage/editProfile/DeleteAccount.tsx, pages/auth/find-password/index.tsx, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx, pages/mypage/index.tsx
pages/auth/find-password/index.tsx
비밀번호 찾기 기능 추가
=> 비밀번호 찾기 기능 추가

Hooks/useFilter.tsx, Hooks/useGetReaction.tsx, Hooks/usePost.tsx, Hooks/useUpdateLikes.tsx, components/PostListCard.tsx, components/detail/DetailView.tsx, components/detail/DetailViewProducts.tsx, components/detail/DetailViewSlide.tsx, components/detail/DetailViewText.tsx, components/detail/DetailViewUserInfor.tsx, shared/type.d.ts
Hooks/useGetReaction.tsx
- 의존성 배열로 인한 무한 렌더링을 수정했습니다.
Hooks/usePost.tsx
- React Query 사용해 각 포스트를 불러오는 usePost 훅을 구현했습니다.
- 불필요한 데이터 fetching 및 map 을 제거했습니다.
- 디테일뷰 페이지 / 포스트에 usePost 훅을 적용했습니다.
- urlpath 로 읽어오는 포스트 id 값을 변수 선언해 정리합니다.
components/detail/DetailViewProducts.tsx
components/detail/DetailViewSlide.tsx
components/detail/DetailViewText.tsx
components/detail/DetailViewUserInfor.tsx
- usePost 로 불러온 데이터를 적용시켰습니다.
Hooks/useUpdateLikes.tsx
- React Query 사용해 좋아요를 업데이트하는 useUpdateLikes 훅을 구현했습니다.
- 포스트 리스트 페이지 / 포스트 카드의 좋아요 업데이트 로직을 구현했습니다. (postListMutate)
- 디테일뷰 페이지 / 포스트 의 좋아요 업데이트 로직을 구현했습니다. (postMutate)
components/PostListCard.tsx
- 포스트 리스트 페이지 / 포스트 카드에 useUpdateLikes 훅을 적용합니다.
components/detail/DetailViewUserInfor.tsx
- 디테일뷰 페이지 / 포스트에 …
=> 좋아요 업데이트 & 디테일 뷰 페이지 Read / React Query 적용한 훅으로 리펙토링

components/mypage/ProfileEditModal.tsx, components/mypage/editProfile/ChangePassword.tsx, components/mypage/editProfile/ChangeProfile.tsx, pages/auth/find-password/index.tsx, pages/auth/sns-nickname/index.tsx, pages/mypage/index.tsx
폰트 볼드 수정
components/mypage/editProfile/ChangePassword.tsx
비밀번호 찾기 CSS 수정
auth.currentUser가 아니라 userinfo에서 정보 가져오게 바꿈
pages/auth/find-password/index.tsx
유효성 검증 커스텀훅으로 빼기
=> mypage bug fix

pages/auth/find-password/index.tsx, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx
pages/auth/find-password/index.tsx
회원가입시 데이터 구조 변경
비밀번호 찾기시 소셜로그인 유저 검증
=> 회원가입시 데이터 구조 변경, 비밀번호 찾기시 소셜로그인 유저 검증

components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteProductCard.tsx, components/detail-write/DetailWriteSearch.tsx, components/detail/DetailView.tsx, components/detail/DetailViewSlide.tsx, components/ui/CustomButton.tsx, pages/detail/write/[id]/edit.tsx, pages/detail/write/index.tsx
- 선택한 제품이 들어가는 슬라이드 카드에 delete기능 추가
- 약간의 UI 변경
components/detail-write/DetailWriteSearch.tsx
- 직접 입력란 기능 잠시 주석처리함(아직 구현이 안 됨)
- 수정, 삭제 버튼에 커스텀 모달 적용하여 버튼 클릭 시 모달 팝업이 생성됨
components/detail/DetailViewSlide.tsx
-detail이라고 되어있던 부분에서 에러가 나서 post로 변경함
components/detail/DetailViewSlide.tsx
- 포스트 이미지2가 들어가는 부분의 주석을 다시 살림
pages/detail/write/[id]/edit.tsx
- edit페이지에서 postImage에 대한 이니셜 밸류값을 array에 집어넣어 다시 지정해줌
=> 글쓰기 페이지 UI 수정, 이미지 미리보기 및 이미지 다중 업로드 기능 추가(WIP)

components/detail-write/DetailWriteForm.tsx, components/detail/DetailView.tsx, components/mypage/contents/PostCard.tsx, components/mypage/contents/ScrapCard.tsx
- 중복되는 코드 삭제
components/mypage/contents/PostCard.tsx
components/mypage/contents/ScrapCard.tsx
- 포스트 카드, 스크랩 카드에 정규식 적용
=> 중복되는 코드 삭제, 포스트 카드, 스크랩 카드에 정규식 적용

components/mypage/editProfile/ChangeProfile.tsx, components/post-list/SignUpModal.tsx, package.json, pages/auth/sign-up/index.tsx, pages/auth/sns-nickname/index.tsx, pages/mypage/index.tsx, pages/post-list/index.tsx
CSS 수정
components/post-list/SignUpModal.tsx
모달컴포넌트 추가
package.json
browser-image-compression 추가
router.push 관련동작추가
router.push 관련동작추가
useCheckUser 추가
pages/post-list/index.tsx
모달 관련 동작 추가
=> ✨ Feat: 회원가입시 환영 모달 추가 #31

components/mypage/editProfile/ChangeProfile.tsx
removeQueries를 invalidateQueries로 변경, 변경완료시 모달닫기 주석처리(임시)
=> 🚑 !HOTFIX: removeQueries를 invalidateQueries로 변경, 변경완료시 모달닫기 주석처리(임시) #35

components/detail-write/DetailWriteForm.tsx
데이터 get 요청 url 변경
- 데이터를 요청하는 곳의 url을 변경합니다
=> version 1.03

components/detail/DetailViewText.tsx, pages/_app.tsx
pages/_app.tsx
- 중복된 카카오톡 javascript key 주석 처리
=> 카카오톡 에러 수정 임시 테스트

components/mypage/contents/MyFollow.tsx, components/mypage/contents/MyPost.tsx, components/mypage/contents/MyScrap.tsx, components/ui/authUi/CustomAuthUI.tsx, components/ui/authUi/CustomErrorMessage.tsx, components/ui/authUi/CustomInput.tsx
components/mypage/contents/MyFollow.tsx
components/mypage/contents/MyPost.tsx
components/mypage/contents/MyScrap.tsx
마이페이지 물음표 해상도 변경
components/ui/authUi/CustomAuthUI.tsx
components/ui/authUi/CustomErrorMessage.tsx
components/ui/authUi/CustomInput.tsx
auth 페이지용 커스텀 UI 추가
=> auth 페이지용 커스텀 UI 추가, 마이페이지 물음표 해상도 변경 #30 #31 #32 #37

components/Footer.tsx, components/GlobalNavigationBar.tsx, components/detail-write/DetailWriteForm.tsx, pages/post-list/index.tsx
page/_app.tsx
- 중복된 카카오톡 key 주석처리
=> kakao 임시테스트 

components/post-list/SignUpModal.tsx, pages/auth/sns-nickname/index.tsx, pages/post-list/index.tsx
components/post-list/SignUpModal.tsx
pages/post-list/index.tsx
회원가입 모달정보를 router.push 쿼리에서 로컬스토리지로 변경했습니다.
=> 🔨 Fix: 회원가입 모달 오류 수정#31

components/detail/DetailViewText.tsx
components/detail/DetailViewText.tsx
- kakaolink Url 버그 수정
=>  kakaolink Url 버그 수정

components/detail/DetailViewText.tsx
components/detail/DetailViewText.tsx
- kakaolink Url 버그 수정
=> Fix: kakaolink Url 버그 수정

components/detail/DetailView.tsx, components/detail/DetailViewProducts.tsx, components/detail/DetailViewSlide.tsx, components/detail/DetailViewText.tsx, components/detail/DetailViewUserInfor.tsx, components/post-list/Comment/Comment.tsx, components/post-list/Comment/CommentList.tsx, components/ui/CustomModal.tsx, components/ui/skeleton/Skeleton.tsx, components/ui/skeleton/SkeletonDetail.tsx, components/ui/skeleton/SkeletonPostCard.tsx, pages/post-list/index.tsx, public/images/modify_icon.svg
pages/post-list/index.tsx
components/detail/DetailViewProducts.tsx
components/detail/DetailViewSlide.tsx
components/detail/DetailViewUserInfor.tsx
components/post-list/Comment/Comment.tsx
components/post-list/Comment/CommentList.tsx
- 반응형 UI 수정
components/detail/DetailViewUserInfor.tsx
public/images/modify_icon.svg
- 수정삭제 아이콘 및 자리 이동
components/ui/skeleton/Skeleton.tsx
components/ui/skeleton/SkeletonDetail.tsx
components/ui/skeleton/SkeletonPostCard.tsx
- 스켈레톤 UI 컴포넌트 추가
pages/post-list/index.tsx
- 로딩시 스켈레톤 UI 추가
=> 반응형 수정 및 스켈레톤 UI 추가

Hooks/useUserPostList.tsx, components/GlobalNavigationBar.tsx, components/detail-write/DetailWriteForm.tsx, components/detail/DetailView.tsx, components/detail/DetailViewProducts.tsx, components/detail/DetailViewSlide.tsx, components/detail/DetailViewText.tsx, components/detail/DetailViewUserInfor.tsx, components/mypage/CategoryButton.tsx, components/mypage/ProfileEditModal.tsx, components/mypage/contents/FollowingCard.tsx, components/mypage/contents/MyFollow.tsx, components/mypage/contents/MyPost.tsx, components/mypage/contents/MyScrap.tsx, components/mypage/contents/PostCard.tsx, components/mypage/contents/ScrapCard.tsx, components/mypage/editProfile/ChangePassword.tsx, components/mypage/editProfile/ChangeProfile.tsx, components/mypage/editProfile/DeleteAccount.tsx, components/post-list/Comment/Comment.tsx, components/post-list/Comment/CommentList.tsx, components/ui/CustomModal.tsx, components/ui/skeleton/Skeleton.tsx, components/ui/skeleton/SkeletonDetail.tsx, components/ui/skeleton/SkeletonPostCard.tsx, pages/auth/sign-in/index.tsx, pages/auth/sign-up/index.tsx, pages/mypage/index.tsx, pages/post-list/index.tsx, public/images/modify_icon.svg
=> version 1.05

components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteSearch.tsx, components/detail-write/DetailWriteSearchModal.tsx
components/detail-write/DetailWriteSearchModal.tsx
- 검색 모달 오버레이 크기를 변경합니다 (45rem -> 75vh)
- api get하는 url 변경했습니다 
components/detail-write/DetailWriteSearch.tsx
- 검색 모달 카테고리를 추가했습니다
=> 검색 모달 오버레이 크기 변경, api url 변경, 카테고리 추가

components/detail-write/DetailWriteForm.tsx
=> 글쓰기 페이지 이미지 업로드 문구 수정

pages/post-list/index.tsx
=> version 1.08

components/detail-write/DetailWriteForm.tsx, components/detail-write/DetailWriteProductCard.tsx, components/detail-write/DetailWriteSearch.tsx, components/detail/DetailView.tsx, components/detail/DetailViewSlide.tsx, components/main/MobileMenu.tsx, components/post-list/Comment/CommentWrite.tsx, pages/_app.tsx
components/detail-write/DetailWriteSearch.tsx
- Design: 글쓰기 UI 수정
=> Design: 글쓰기 UI 수정

Hooks/useCheckLogin.tsx, Hooks/useCheckUser.tsx, components/detail/DetailViewUserInfor.tsx, components/post-list/PostListCard.tsx, pages/auth/sign-in/index.tsx, pages/auth/sns-nickname/index.tsx, pages/detail/write/index.tsx, pages/mypage/index.tsx
Hooks/useCheckUser.tsx
-  useCheckUser 내에 유저 정보 유무 상태 값인 userExist를 구현했습니다.
- userExist 여부로 좋아요, 스크랩, 팔로우, 마이페이지 접근을 제한했습니다.
components/detail/DetailViewUserInfor.tsx
- useCheckUser 훅을 적용했습니다.
=> 유저정보유무 체크 훅 useCheckUser 수정 및 적용

components/mypage/editProfile/DeleteAccount.tsx, components/ui/authUi/CustomAuthUI.tsx, pages/auth/sns-nickname/index.tsx
components/mypage/editProfile/DeleteAccount.tsx
회원탈퇴 회원인증 방식변경, 비밀번호 입력추가
components/ui/authUi/CustomAuthUI.tsx
커스텀컴포넌트 요소수정
=> :hammer:Fix : 회원탈퇴 회원인증 방식변경

Hooks/useCheckLogin.tsx, Hooks/useCheckUser.tsx, README.md, components/detail/DetailViewUserInfor.tsx, components/mypage/editProfile/DeleteAccount.tsx, components/post-list/PostListCard.tsx, components/ui/authUi/CustomAuthUI.tsx, pages/auth/sign-in/index.tsx, pages/auth/sns-nickname/index.tsx, pages/detail/write/index.tsx, pages/mypage/index.tsx
=> version 1.11
